# Generated by Django 5.0.6 on 2024-07-05 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0003_remove_clientprofile_client_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_business',
            field=models.CharField(max_length=255, verbose_name="Client's Business"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_email',
            field=models.EmailField(max_length=254, unique=True, verbose_name="Client's Email"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_event_space',
            field=models.CharField(max_length=255, verbose_name="Client's Event Space"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Client's First Name"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Client's Last Name"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Client's Phone"),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='client_special_needs',
            field=models.TextField(blank=True, null=True, verbose_name="Client's Special Needs"),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_submissions', to='frostapi.clientprofile', verbose_name='Client Profile'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='condition',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Condition'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='customer_email',
            field=models.EmailField(max_length=254, verbose_name="Customer's Email"),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='frostapi.clientprofile', verbose_name='Client Profile'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_host',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Host'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Image Upload'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_name',
            field=models.CharField(max_length=255, verbose_name='Event Name'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
