# Generated by Django 5.0.6 on 2024-07-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0004_clientprofile_slug_alter_clientprofile_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='event_image',
            field=models.ImageField(blank=True, upload_to='frost', verbose_name='Image Upload'),
        ),
    ]
