# Generated by Django 5.0.6 on 2024-07-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0007_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdata',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
