# Generated by Django 5.0.6 on 2024-07-10 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0008_eventdata_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
