# Generated by Django 5.0.6 on 2024-07-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0011_alter_clientprofile_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='client_profile',
        ),
    ]
