# Generated by Django 5.0.7 on 2024-07-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0013_remove_eventdata_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Timestamp'),
        ),
    ]
