# Generated by Django 5.0.7 on 2024-07-26 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0014_alter_contactformsubmission_time_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_question', models.CharField(max_length=100, null=True, verbose_name='FAQ Question')),
                ('faq_answer', models.TextField(null=True, verbose_name='FAQ Answer')),
            ],
            options={
                'verbose_name_plural': 'FAQ Data',
            },
        ),
        migrations.CreateModel(
            name='GalleryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_media_title', models.CharField(max_length=100, null=True, verbose_name='Image/Video Title')),
                ('gallery_media_description', models.TextField(null=True, verbose_name='Image/Video Description')),
                ('gallery_media_image', models.ImageField(blank=True, null=True, upload_to='gallery', verbose_name='Image Upload')),
                ('gallery_media_video', models.URLField()),
                ('gallery_media_choices', models.TextField(choices=[('Image', 'Image'), ('Video', 'Video')], default='Image', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Gallery Data',
            },
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_description',
            field=models.TextField(blank=True, null=True, verbose_name='Event Description'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 26, 8, 40, 46, 243218), verbose_name='Event Time'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_venue',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Event Venue'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 8, 40, 46, 243218), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event Name'),
        ),
    ]
