# Generated by Django 5.0.7 on 2024-07-26 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0015_faq_data_gallerydata_eventdata_event_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy_question', models.CharField(max_length=100, null=True, verbose_name='Policy Question')),
                ('Policy_answer', models.TextField(null=True, verbose_name='Policy Answer')),
            ],
            options={
                'verbose_name_plural': 'Policy Data',
            },
        ),
        migrations.RenameModel(
            old_name='FAQ_Data',
            new_name='FAQData',
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 26, 9, 7, 0, 578633), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 26, 9, 7, 0, 578633), verbose_name='Event Time'),
        ),
    ]
