# Generated by Django 5.0.7 on 2024-07-27 12:17

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0016_policydata_rename_faq_data_faqdata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqdata',
            name='faq_answer',
        ),
        migrations.RemoveField(
            model_name='faqdata',
            name='faq_question',
        ),
        migrations.RemoveField(
            model_name='policydata',
            name='Policy_answer',
        ),
        migrations.RemoveField(
            model_name='policydata',
            name='Policy_question',
        ),
        migrations.AddField(
            model_name='faqdata',
            name='faq_descrip',
            field=models.TextField(null=True, verbose_name='FAQ Description'),
        ),
        migrations.AddField(
            model_name='faqdata',
            name='faq_title',
            field=models.CharField(max_length=100, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AddField(
            model_name='gallerydata',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='gallery Slug'),
        ),
        migrations.AddField(
            model_name='policydata',
            name='Policy_descrip',
            field=models.TextField(null=True, verbose_name='Policy Description'),
        ),
        migrations.AddField(
            model_name='policydata',
            name='Policy_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Policy Title'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 27, 6, 17, 46, 180060), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 27, 6, 17, 46, 180060), verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='gallerydata',
            name='gallery_media_video',
            field=models.URLField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
