# Generated by Django 5.0.7 on 2024-07-28 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0019_alter_eventdata_event_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 28, 16, 28, 31, 887735), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 28, 16, 28, 31, 887735), verbose_name='Event Time'),
        ),
    ]
