# Generated by Django 5.0.7 on 2024-08-01 05:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0021_eventdata_time_stamp_alter_eventdata_event_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'ordering': ['event_date']},
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 7, 31, 23, 15, 25, 767672), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 7, 31, 23, 15, 25, 767672), verbose_name='Event Time'),
        ),
    ]
