# Generated by Django 5.0.7 on 2024-08-02 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0022_alter_eventdata_options_alter_eventdata_event_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactformsubmission',
            name='message_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 0, 14, 42, 930247), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 2, 0, 14, 42, 930247), verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='faqdata',
            name='faq_descrip',
            field=models.TextField(blank=True, null=True, verbose_name='FAQ Description'),
        ),
        migrations.AlterField(
            model_name='faqdata',
            name='faq_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FAQ Title'),
        ),
        migrations.AlterField(
            model_name='gallerydata',
            name='gallery_media_description',
            field=models.TextField(blank=True, null=True, verbose_name='Image/Video Description'),
        ),
        migrations.AlterField(
            model_name='gallerydata',
            name='gallery_media_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Image/Video Title'),
        ),
        migrations.AlterField(
            model_name='policydata',
            name='Policy_descrip',
            field=models.TextField(blank=True, null=True, verbose_name='Policy Description'),
        ),
        migrations.AlterField(
            model_name='policydata',
            name='Policy_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Policy Title'),
        ),
    ]
