# Generated by Django 5.0.7 on 2024-08-02 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0024_alter_contactformsubmission_client_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactformsubmission',
            name='condition',
        ),
        migrations.AddField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 12, 43, 41, 626436), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='customer_email',
            field=models.EmailField(blank=True, default='Enter Email Address Here', max_length=254, verbose_name="Customer's Email"),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='message',
            field=models.TextField(default='Tell us about your event', verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 2, 12, 43, 41, 627443), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 2, 12, 43, 41, 627443), verbose_name='Event Time'),
        ),
    ]
