# Generated by Django 5.0.7 on 2024-08-05 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0025_remove_contactformsubmission_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 44, 5, 363545), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 5, 12, 44, 5, 364545), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 5, 12, 44, 5, 364545), verbose_name='Event Time'),
        ),
    ]
