# Generated by Django 5.0.7 on 2024-08-07 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0027_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 16, 29, 3, 106258), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 7, 16, 29, 3, 106767), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 7, 16, 29, 3, 106767), verbose_name='Event Time'),
        ),
    ]
