# Generated by Django 5.0.7 on 2024-08-08 17:55

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0029_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextSliderBottom',
            fields=[
                ('bottom_slider_title', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('bottom_slider_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Bottom Text')),
            ],
        ),
        migrations.CreateModel(
            name='TextSliderTop',
            fields=[
                ('top_slider_title', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('top_slider_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Slider Top Text')),
            ],
        ),
        migrations.AddField(
            model_name='eventdata',
            name='artist_facebook',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='artist_instagram',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='artist_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='artist_spotify',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='spotify'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='artist_youtube',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='youtube'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_genre',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Event Genre'),
        ),
        migrations.AddField(
            model_name='eventdata',
            name='event_type',
            field=models.CharField(blank=True, choices=[('Music', 'Music'), ('Theatre', 'Theatre'), ('Wrestling', 'Wrestling'), ('Market', 'Market'), ('Private Party', 'Private Party')], max_length=20, null=True, verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 8, 11, 55, 37, 298655), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 8, 11, 55, 37, 300663), verbose_name='Event Time'),
        ),
    ]
