# Generated by Django 5.0.7 on 2024-08-09 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0031_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsliderbottom',
            name='active_text',
            field=models.BooleanField(default=False, verbose_name='Active Text'),
        ),
        migrations.AddField(
            model_name='textslidertop',
            name='active_text',
            field=models.BooleanField(default=False, verbose_name='Active Text'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 5, 26, 357853), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 9, 9, 5, 26, 357853), verbose_name='Event Time'),
        ),
    ]
