# Generated by Django 5.0.7 on 2024-08-09 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0032_textsliderbottom_active_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 9, 8, 20, 468181), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 9, 9, 8, 20, 469183), verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='textsliderbottom',
            name='active_text',
            field=models.BooleanField(default=False, null=True, verbose_name='Active Text'),
        ),
        migrations.AlterField(
            model_name='textslidertop',
            name='active_text',
            field=models.BooleanField(default=False, null=True, verbose_name='Active Text'),
        ),
    ]
