# Generated by Django 5.0.7 on 2024-08-09 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0033_alter_contactformsubmission_event_date_request_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerydata',
            name='gallery_media_choices',
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 9, 13, 4, 18, 849266), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 9, 13, 4, 18, 850270), verbose_name='Event Time'),
        ),
    ]
