# Generated by Django 5.0.7 on 2024-08-10 18:52

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0034_remove_gallerydata_gallery_media_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerydata',
            name='gallery_media_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Image/Video Date'),
        ),
        migrations.AddField(
            model_name='gallerydata',
            name='gallery_media_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=100, null=True, verbose_name='Image/Video Author'),
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 12, 52, 18, 826298), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 10, 12, 52, 18, 827813), verbose_name='Event Time'),
        ),
    ]
