# Generated by Django 5.0.7 on 2024-08-10 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frostapi', '0035_gallerydata_gallery_media_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventdata',
            options={'ordering': ['event_date'], 'verbose_name': 'Event Data', 'verbose_name_plural': 'Event Data'},
        ),
        migrations.AlterModelOptions(
            name='gallerydata',
            options={'verbose_name': 'Gallery Data', 'verbose_name_plural': 'Gallery Data'},
        ),
        migrations.AlterField(
            model_name='contactformsubmission',
            name='event_date_request',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 10, 14, 55, 34, 185714), verbose_name='Event Date'),
        ),
        migrations.AlterField(
            model_name='eventdata',
            name='event_time',
            field=models.TimeField(default=datetime.datetime(2024, 8, 10, 14, 55, 34, 187242), verbose_name='Event Time'),
        ),
        migrations.AlterField(
            model_name='gallerydata',
            name='gallery_media_type',
            field=models.CharField(blank=True, choices=[('image', 'image'), ('video', 'video')], max_length=100, null=True, verbose_name='Media Type'),
        ),
    ]
